spring.application.name=coursemanagement
#spring.data.mongodb.uri=mongodb+srv://it22278944:nL6kiAUrqQwBWtmC@itpm-project.k7b3m.mongodb.net/timesyncdb-dev?retryWrites=true&w=majority&appName=ITPM-PROJECT
spring.data.mongodb.uri=mongodb+srv://gimhanii2002:1234@cluster0.1vlnhmm.mongodb.net/spring?retryWrites=true&w=majority&appName=Cluster0
server.port = 8082
#server.port = 8083

# Actuator endpoints configuration
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# Service info
info.app.name=Course Management Service
info.app.description=Academic Scheduler Course Management
info.app.version=1.0.0
