# Example k8s/usermanager-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermanager
  template:
    metadata:
      labels:
        app: usermanager
    spec:
      containers:
      - name: usermanager
        image: ravinbanda/usermanager:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: usermanager
spec:
  selector:
    app: usermanager
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP